import { useState } from "react";
import ToolLayout from "@/components/ToolLayout";
import FileUpload from "@/components/FileUpload";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { BrainCircuit, Download, Eye, EyeOff, CheckCircle2, XCircle } from "lucide-react";
import { extractTextFromPdf } from "@/lib/pdfTextExtract";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { saveAs } from "file-saver";

type QuizType = "mcq" | "truefalse" | "short";

interface Question {
  question: string;
  options: string[];
  answer: string;
  explanation: string;
}

const QuizGenerator = () => {
  const [files, setFiles] = useState<File[]>([]);
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState(0);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [quizType, setQuizType] = useState<QuizType>("mcq");
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, string>>({});
  const [showAnswers, setShowAnswers] = useState<Record<number, boolean>>({});
  const [showAllAnswers, setShowAllAnswers] = useState(false);
  const { toast } = useToast();

  const handleGenerate = async () => {
    if (files.length === 0) return;
    setProcessing(true);
    setProgress(20);
    setQuestions([]);
    setSelectedAnswers({});
    setShowAnswers({});
    setShowAllAnswers(false);

    try {
      const text = await extractTextFromPdf(files[0]);
      setProgress(50);

      if (!text.trim()) {
        toast({ title: "Error", description: "Could not extract text from PDF.", variant: "destructive" });
        setProcessing(false);
        return;
      }

      const { data, error } = await supabase.functions.invoke("ai-quiz", {
        body: { text, quizType, count: 10 },
      });

      setProgress(90);
      if (error) throw error;
      setQuestions(data.questions || []);
      setProgress(100);
    } catch (e: any) {
      toast({ title: "Error", description: e.message || "Failed to generate quiz.", variant: "destructive" });
    } finally {
      setProcessing(false);
    }
  };

  const selectAnswer = (qIndex: number, answer: string) => {
    setSelectedAnswers((prev) => ({ ...prev, [qIndex]: answer }));
  };

  const toggleAnswer = (qIndex: number) => {
    setShowAnswers((prev) => ({ ...prev, [qIndex]: !prev[qIndex] }));
  };

  const getScore = () => {
    let correct = 0;
    questions.forEach((q, i) => {
      if (selectedAnswers[i] === q.answer) correct++;
    });
    return correct;
  };

  const downloadQuizPdf = async () => {
    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
    const fontSize = 10;
    const margin = 50;

    let page = doc.addPage();
    let y = page.getHeight() - margin;

    const writeLine = (text: string, bold = false) => {
      if (y < margin) {
        page = doc.addPage();
        y = page.getHeight() - margin;
      }
      page.drawText(text.slice(0, 90), { x: margin, y, size: fontSize, font: bold ? boldFont : font, color: rgb(0.1, 0.1, 0.1) });
      y -= fontSize + 6;
    };

    writeLine("Quiz Generated by My Love PDF", true);
    y -= 10;

    questions.forEach((q, i) => {
      writeLine(`Q${i + 1}: ${q.question}`, true);
      q.options.forEach((opt) => writeLine(`   ${opt}`));
      writeLine(`Answer: ${q.answer}`);
      if (q.explanation) writeLine(`Explanation: ${q.explanation}`);
      y -= 8;
    });

    const pdfBytes = await doc.save();
    saveAs(new Blob([pdfBytes.buffer as ArrayBuffer], { type: "application/pdf" }), "quiz.pdf");
  };

  const types: { value: QuizType; label: string }[] = [
    { value: "mcq", label: "Multiple Choice" },
    { value: "truefalse", label: "True / False" },
    { value: "short", label: "Short Answer" },
  ];

  return (
    <ToolLayout
      title="PDF Quiz Generator"
      description="Upload study material and generate quiz questions automatically using AI."
      category="ai"
      icon={<BrainCircuit className="h-7 w-7" />}
      metaTitle="PDF Quiz Generator — AI Study Tool | My Love PDF"
      metaDescription="Upload lecture notes or study material and instantly generate MCQ, true/false, or short answer quizzes."
    >
      <div className="space-y-6">
        <FileUpload accept=".pdf" multiple={false} onFilesChange={setFiles} files={files} label="Upload study material (PDF)" />

        {files.length > 0 && questions.length === 0 && (
          <div className="space-y-4">
            <div className="flex flex-wrap gap-2">
              {types.map((t) => (
                <Button key={t.value} variant={quizType === t.value ? "default" : "outline"} size="sm" onClick={() => setQuizType(t.value)} className="rounded-xl">
                  {t.label}
                </Button>
              ))}
            </div>
            {processing && <Progress value={progress} className="h-2" />}
            <Button onClick={handleGenerate} disabled={processing} size="lg" className="w-full rounded-xl">
              <BrainCircuit className="mr-2 h-5 w-5" />
              {processing ? "Generating…" : "Generate Quiz"}
            </Button>
          </div>
        )}

        {questions.length > 0 && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h2 className="font-display text-xl font-bold text-foreground">
                Quiz — {questions.length} Questions
              </h2>
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={() => setShowAllAnswers(!showAllAnswers)} className="rounded-xl">
                  {showAllAnswers ? <EyeOff className="mr-1 h-4 w-4" /> : <Eye className="mr-1 h-4 w-4" />}
                  {showAllAnswers ? "Hide All" : "Reveal All"}
                </Button>
                <Button variant="outline" size="sm" onClick={downloadQuizPdf} className="rounded-xl">
                  <Download className="mr-1 h-4 w-4" /> Download PDF
                </Button>
              </div>
            </div>

            {questions.map((q, i) => (
              <div key={i} className="rounded-2xl border border-border bg-card p-5 shadow-card space-y-3">
                <p className="font-display text-sm font-semibold text-foreground">
                  Q{i + 1}. {q.question}
                </p>

                {q.options.length > 0 && (
                  <div className="grid gap-2">
                    {q.options.map((opt, oi) => {
                      const isSelected = selectedAnswers[i] === opt;
                      const revealed = showAnswers[i] || showAllAnswers;
                      const isCorrect = opt === q.answer;
                      return (
                        <button
                          key={oi}
                          onClick={() => selectAnswer(i, opt)}
                          className={`flex items-center gap-2 rounded-xl border px-4 py-2.5 text-left text-sm transition-all ${
                            revealed && isCorrect
                              ? "border-green-500 bg-green-50 text-green-800"
                              : revealed && isSelected && !isCorrect
                              ? "border-red-400 bg-red-50 text-red-700"
                              : isSelected
                              ? "border-primary bg-primary/5 text-foreground"
                              : "border-border hover:border-primary/40"
                          }`}
                        >
                          {revealed && isCorrect && <CheckCircle2 className="h-4 w-4 shrink-0 text-green-600" />}
                          {revealed && isSelected && !isCorrect && <XCircle className="h-4 w-4 shrink-0 text-red-500" />}
                          {opt}
                        </button>
                      );
                    })}
                  </div>
                )}

                <div className="flex items-center gap-2">
                  <Button variant="ghost" size="sm" onClick={() => toggleAnswer(i)} className="text-xs">
                    {showAnswers[i] || showAllAnswers ? "Hide Answer" : "Show Answer"}
                  </Button>
                </div>

                {(showAnswers[i] || showAllAnswers) && (
                  <div className="rounded-xl bg-secondary/50 p-3 text-sm">
                    <p className="font-semibold text-foreground">Answer: {q.answer}</p>
                    {q.explanation && <p className="mt-1 text-muted-foreground">{q.explanation}</p>}
                  </div>
                )}
              </div>
            ))}

            {Object.keys(selectedAnswers).length === questions.length && (
              <div className="rounded-2xl border border-primary bg-primary/5 p-5 text-center">
                <p className="font-display text-2xl font-bold text-primary">
                  Score: {getScore()} / {questions.length}
                </p>
              </div>
            )}

            <div className="flex gap-2">
              <Button variant="ghost" onClick={() => { setQuestions([]); setFiles([]); setSelectedAnswers({}); setShowAnswers({}); }} className="rounded-xl">
                Generate Another Quiz
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">Your files are private and automatically deleted after processing.</p>
          </div>
        )}
      </div>
    </ToolLayout>
  );
};

export default QuizGenerator;
